### ISSUE TITLE
Miscellaneous Cleanup Tasks

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.SingleProcessApp#13]
# Miscellaneous Cleanup Tasks

Remaining minor things left over from code review that don't fit under any other category. Just the small stuff.

## Points of Feedback

1. **Unused Loggers**: Many constructors in `NexusMods.SingleProcess`, such as in `ADirector`, contain unused loggers, please remove them from constructor if they are not needed.

2. **Required Documentation**: The project documentation is missing some info on bootstrapping in 'Getting Started'. For example, existence of classes such as `StartupDirector`, or creating verbs.

3. **Note on KeepAliveToken**: It should be documented that `TrySetResult` in `KeepAliveToken` implementation is a blocking method call, this is not commonly known and can be crucial for understanding the code's behavior.

4. **Small Clarification**: In the `Serializer.SendAsync` method, the code writes to both `BinaryWriter` and `Stream`. It should be explicitly commented that these writes are actually directed to the same output for clarity.

5. **Missing XML Docs**: Around 50 warnings unresolved.

**Comment by halgari** [comment]
The behavior of KeepAliveToken is not the responsibility of the KeepAliveToken. I've wrapped it in a boolean so the spinlock case will never happen. 

Handled the warnings, and removed the logger commands. 

We'll loop back and write more docs sometime in the futre if/when we ever want to use this in another projects. I reworked the code so that usages of stream use `_binaryWriter.BaseStream` to remove the need for additional documentation
